---
title: "Assignment 2"
description: |
  Week 1 & 2
author:
  - name: Walid Medani 
    url: https://walidmedani.github.io/networks-blog/
    affiliation: UMass Amherst
    affiliation_url: 
date: 02-02-2022
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```

```{r include=FALSE}
library(distill)
create_post("Assignment_2")
```
```{r include=FALSE}
library(distill)
create_post("Assignment_3")
```

```{r include=FALSE}
library(distill)
create_post("Assignment_4")
```

```{r include=FALSE}
library(distill)
create_post("Assignment_5")
```

```{r include=FALSE}
library(distill)
create_post("Assignment_6")
```

```{r include=FALSE}
library(distill)
create_post("Assignment_7")
```

```{r include=FALSE}
library(distill)
create_post("Assignment_8")
```

```{r include=FALSE}
library(distill)
create_post("Bolivia")
```

```{r include=FALSE}
library(distill)
create_post("Blog 1")
```